### ISSUE TITLE
"TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by creativedude** [ibraheem-ghazi/node-red-contrib-sentrynode#1]
I have attached the sentry node to a catch:all node, and created a test flow with an undefined function to simulate an error.
I have also tried it with a catch nod that focusses only on certain nodes.

Unfortunately the payload on the sentry node remains: {sent:false} and the debug message "TypeError: Cannot read property '1' of null" displays for the sentry node.
I have added a DSN and name to the node (redacted for privacy purposes). 
Happy to provide more information on request.

node-red-log entry for the error:
`[error] [sentry:Sentry debugger] TypeError: Cannot read property '1' of null`

Heres my flow:
`[
    {
        "id": "7f7d6154.e6b79",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "f04ee96a.26eb98",
        "type": "inject",
        "z": "7f7d6154.e6b79",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 140,
        "wires": [
            [
                "3b5a7369.981f6c"
            ]
        ]
    },
    {
        "id": "3b5a7369.981f6c",
        "type": "function",
        "z": "7f7d6154.e6b79",
        "name": "I am a function",
        "func": "msg.testFn();\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 300,
        "y": 140,
        "wires": [
            [
                "7332b7ca.c785e8"
            ]
        ]
    },
    {
        "id": "2b0d7670.eb6d2a",
        "type": "catch",
        "z": "7f7d6154.e6b79",
        "name": "",
        "scope": null,
        "uncaught": false,
        "x": 150,
        "y": 320,
        "wires": [
            [
                "79189ef5.1a992"
            ]
        ]
    },
    {
        "id": "79189ef5.1a992",
        "type": "sentry",
        "z": "7f7d6154.e6b79",
        "name": "Sentry debugger",
        "dsn": "https://secret.ingest.sentry.io/secretnr",
        "environment": "debug",
        "x": 380,
        "y": 320,
        "wires": [
            [
                "aaa0d3f1.bf83f",
                "bdeac8dc.e7ed88"
            ]
        ]
    },
    {
        "id": "aaa0d3f1.bf83f",
        "type": "debug",
        "z": "7f7d6154.e6b79",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "error",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 580,
        "y": 360,
        "wires": []
    },
    {
        "id": "bdeac8dc.e7ed88",
        "type": "debug",
        "z": "7f7d6154.e6b79",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 280,
        "wires": []
    },
    {
        "id": "7332b7ca.c785e8",
        "type": "debug",
        "z": "7f7d6154.e6b79",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 140,
        "wires": []
    }
]`

**Comment by draperez** [comment]
I'm having the same issue.

**Comment by mw-muwo** [comment]
hey guys, i had the same issue, fixed it and opened a pull request: https://github.com/ibraheem-ghazi/node-red-contrib-sentrynode/pull/2

als long it isn't merged you can simply use my fork by running 
`npm install --save https://github.com/mw-muwo/node-red-contrib-sentrynode`

**Comment by ibraheem-ghazi** [comment]
Thanks for reporting, and apologize for taking a long time to notice this, I haven't checked the package a long time ago and didn't receive any email related,

@mw-muwo  Thanks for contributing, the pull request https://github.com/ibraheem-ghazi/node-red-contrib-sentrynode/pull/2 has been merged.

The issue will be closed for now, if you have any further questions, let me know
